# Generated by Django 6.1 on 2026-08-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
