# Generated by Django 6.1 on 2026-08-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_loginattempt_supportmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'verbose_name': 'Попытка входа', 'verbose_name_plural': 'Попытки входа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'verbose_name': 'Сообщение в техподдержку', 'verbose_name_plural': 'Сообщения в техподдержку'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
