# Generated by Django 6.1 on 2026-08-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_category_options_alter_loginattempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('total', models.CharField(max_length=20, verbose_name='Сумма')),
                ('items', models.TextField(verbose_name='Товары')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
