# Generated by Django 6.1 on 2026-08-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_score',
            field=models.IntegerField(default=0),
        ),
    ]
