# Generated by Django 6.1 on 2026-08-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1 — Ужасно'), (2, '⭐ 2 — Плохо'), (3, '⭐ 3 — Нормально'), (4, '⭐ 4 — Хорошо'), (5, '⭐ 5 — Отлично')], default=5, verbose_name='Оценка')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
