# Generated by Django 6.1 on 2026-08-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_review_email_review_name_user_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
