# Generated by Django 6.1 on 2026-08-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_promocode_recommendedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.IntegerField(default=1000, verbose_name='Минимальная сумма')),
                ('promo_code_template', models.CharField(default='BONUS', max_length=50, verbose_name='Шаблон промокода')),
                ('discount', models.IntegerField(default=10, verbose_name='Скидка (%)')),
                ('validity_days', models.IntegerField(default=5, verbose_name='Срок действия (дней)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Настройка лояльности',
                'verbose_name_plural': 'Настройки лояльности',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдан')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Промокод пользователя',
                'verbose_name_plural': 'Промокоды пользователей',
            },
        ),
    ]
